### ISSUE TITLE
"curl: (18) transfer closed with outstanding read data remaining" with many concurrent requests

### ISSUE THREAD

**Issue by jonashaag** [weihanglo/sfz#102]
If I use sfz to download ~ 1k files of total size ~ 1.5G using

```
curl --parallel ... >/dev/null
```

I'm getting some

```
curl: (18) transfer closed with outstanding read data remaining
```

This does go away when using `--parallel-max 8` so I assume it has something to do with the number of concurrent requests.

**Comment by weihanglo** [comment]
Could you provide the version number of sfz you currently use?

**Comment by jonashaag** [comment]
Latest from Homebrew installed today

**Comment by weihanglo** [comment]
I guess you're using v0.7.1. Could you confirm  what the output of `sfz --version` is?

**Comment by jonashaag** [comment]
Yes, just checked, it's 0.7.1.

**Comment by weihanglo** [comment]
Thank you for the PR. Unfortunately I have no time working on it. See #108.
