### ISSUE TITLE
Does not work with # in filenames

### ISSUE THREAD

**Issue by bitwave** [weihanglo/sfz#28]
The # character in filenames is not supported.

**Comment by weihanglo** [comment]
Can you provide some examples that can reproduce this issue? It would be really helpful.

**Comment by bitwave** [comment]
```
mkdir foo
cd foo
touch \#123
sfz
```
navigate to page and click on the file.
http://localhost/#123 is interpreted as html anchor and not as filename.

**Comment by weihanglo** [comment]
Fixed at 5601d653e881963803caeed598f49c0f2be9c5c9.
I did not have time to do more robust tests. It just passes some manual tests and works.
