### ISSUE TITLE
404 Not Found after two folders

### ISSUE THREAD

**Issue by Songtronix** [weihanglo/sfz#31]
Everything works fine. However once I go into two folders like ``localhost:5000/folder1/folder2`` I get a ``404 Not Found`` error for files and folders I want to access.

**OS:** Windows 10
Installed via ``cargo install sfz``

**Comment by weihanglo** [comment]
I cannot reproduce this issue on macOS. Did you run `sfz` on Linux subsystem or just Windows cmd?

**Comment by Songtronix** [comment]
@weihanglo just windows cmd.

**Comment by weihanglo** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/14314532/64476651-19505100-d1c4-11e9-9085-5682b15c4814.png">

Fixed in 0.0.4. Just `cargo uninstall sfz && cargo install sfz`.

**Comment by jbg** [comment]
I just ran `cargo install sfz` for the first time on Linux, and hit this bug. After two folders deep, the links in the auto-generated index are generated wrongly (the first component in the path is duplicated).

**Comment by weihanglo** [comment]
> I just ran `cargo install sfz` for the first time on Linux, and hit this bug. After two folders deep, the links in the auto-generated index are generated wrongly (the first component in the path is duplicated).

@jbg Sorry for the inconvenience. This regression bug has fixed at 0.1.1.
