### ISSUE TITLE
Can't serve files larger than available memory

### ISSUE THREAD

**Issue by guncha** [weihanglo/sfz#33]
I'm trying to download a single large (1.3GB) file from a DO droplet that has 0.8GB of free memory and the process is immediately killed by the scary `oom_killer`. This happens with both `aria2c` which tries a range request first and `curl` which doesn't, by default.

Using `sfz-0.0.3-x86_64-unknown-linux-musl.tar.gz` downloaded from the GitHub releases.

I'm happy to provide more details if you need anything else.

**Comment by weihanglo** [comment]
This can be resolved by using some asynchronous fs module like `tokio::fs` to avoid read the whole chunk into memory. I'll check it soon.

**Comment by smackysnacks** [comment]
I just ran into this issue myself when trying to send a 30GB file to another machine on my LAN. I believe using something like [sendfile](https://man7.org/linux/man-pages/man2/sendfile.2.html) on Linux/MacOS or [TransmitFile](https://docs.microsoft.com/en-us/windows/win32/api/mswsock/nf-mswsock-transmitfile) on Windows would avoid the need to load the file into memory before sending.

**Comment by weihanglo** [comment]
You are right. We may leverage tokio's stream read to overcome this issue. Unfortunately I am relocating to a new place recently. Will come back to look into this once settling down. Sorry for the inconvenience.
