### ISSUE TITLE
render_index flag behaves weired

### ISSUE THREAD

**Issue by Perlmint** [weihanglo/sfz#34]
With -r flag, directory request gets a 404 error.

## details
As description in help message, running with `-r` flag should enable rendering index.html for directory request. But with `-r` flag, can't get generated index.html.

Actually, `render_index` flag appends `index.html` to a requested directory path. - https://github.com/weihanglo/sfz/blob/master/src/server/mod.rs#L112
This behaviour will occur 404 error in https://github.com/weihanglo/sfz/blob/master/src/server/mod.rs#L214. So, It can not reach to send_dir function - sending rendered index - on https://github.com/weihanglo/sfz/blob/master/src/server/mod.rs#L229-L230.

**Comment by weihanglo** [comment]
The expected behavior of `-r` flag is to render existed `index.html` instead of generated one. Maybe the description is not clear and need a revise?

**Comment by Perlmint** [comment]
Oh... I misunderstood the description.
I thought "render" means "generated".
In my opinion, appending "instead of generated files list page" to current description or using the words "existing index.html" can make it clear.

**Comment by weihanglo** [comment]
Fixed in c2b683336bf67561e97c84bf20789c3f159f7696.
Thanks for your advice!
