### ISSUE TITLE
Range support off-by-one error

### ISSUE THREAD

**Issue by fasterthanlime** [weihanglo/sfz#39]
When the request header `Range` is set to `bytes=0-`, the last byte is missing from the response.

## Reproduction steps

Create `ohno.txt` with contents:

```shell
$ printf "life" > ohno.txt
$ sfz -Z &
$ curl -s http://localhost:5000/ohno.txt; echo
[30/Jul/2020 18:08:59] "GET /ohno.txt" - 200 OK
life
$ curl -s http://localhost:5000/ohno.txt -H "Range: bytes=0-"; echo
[30/Jul/2020 18:09:16] "GET /ohno.txt" - 206 Partial Content
lif
```

Don't use `echo` to create `ohno.txt`, it would put a newline in it. Some text
editors also automatically insert newlines 

## Additional notes

The HTTP `Range` header is annoying to implement correctly, I recommend writing a bunch of tests around it!

I *think* just doing `end - start + 1` here would fix it: https://github.com/weihanglo/sfz/blob/d3c0b0500e044ebb64c70730fc9cd5068515e252/src/server/send.rs#L162

...but it's the end of the day and I'm tired, so.

**Comment by luser** [comment]
hyper's [`ByteRangeSpec`](https://docs.rs/hyper/0.11.27/hyper/header/enum.ByteRangeSpec.html) seems really useful, but [the conversion to the `Content-Range` header using `to_satisfiable_range`](https://github.com/weihanglo/sfz/blob/809e7dd3bf929f973eac7f35713dd8f23b7a90a9/src/http/range_requests.rs#L60) puts the information in a less useful form. Seems like it'd be less error-prone to simply validate that the range is satisfiable, and then pass the `ByteRangeSpec` down into `send_file_with_range`?

**Comment by fasterthanlime** [comment]
Thanks for the fix @weihanglo! ✨
