### ISSUE TITLE
Option for catch-all redirect

### ISSUE THREAD

**Issue by sporto** [weihanglo/sfz#52]
When building a single page application is common to want all paths (that are not assets) to redirect to the root index.html

E.g.
/ -> /index.html
/users -> /index.html
/users/1 -> /index.html

The SPA handles the routing and shows the correct page. It would be great to have an option for this.

**Comment by weihanglo** [comment]
This is really useful for front-end development! I think we can generalize this idea to a "not found" fallback option.

**Comment by weihanglo** [comment]
Thank you for the PR. Unfortunately I have no time working on it. See #108.
