### ISSUE TITLE
[Feature request] allow the usage of configuration files

### ISSUE THREAD

**Issue by eacp** [weihanglo/sfz#54]
It would be interesting if you could define a configuration file somewhere (eg. ~/.sfzconfig) so the user doesn't need to write all the flags all the time. I could help you with that if you want. It would be an interesting way to learn rust.

**Comment by weihanglo** [comment]
Hmm.... If we are about to implement this feature, we may follow [XDG based directory](https://wiki.archlinux.org/index.php/XDG_Base_Directory) convention, and also the directory convention on Windows such as `%LOCALAPPDATA%`. All aforementioned details seems somewhat overkill for such a small utility. Sorry We have no plan for this feature for now.

Nevertheless, It's indeed interesting. Thank you for giving it! You can look around [other issues](https://github.com/weihanglo/sfz/issues) if they are appealed to you.

**Comment by eacp** [comment]
Thank your for your comments :)
