### ISSUE TITLE
Allow BOTH listing and an index.html file to be the default view for a folder, with a combined mode for renderer and listing

### ISSUE THREAD

**Issue by eacp** [weihanglo/sfz#57]
Hello, I was testing in localhost some code and I executed `sfz -Z -r`, and it works for folders with an `index.html`. The command is also usefull because I can remove the `-r` flag and browse the folder in the browser. However, in this mode I cannot see the default `index.htm`, I have to manually open such file (eg: http://localhost:5000/something/index.html). It would be nice if there was a mode that showed the custom index.html in the directory and the file listing as a backup.

Thanks, and if it sounds interesting, I could help you add such feature.

:)

**Comment by weihanglo** [comment]
Thanks for your suggestion!

Although it is feasible to implement, I am not sure what is the scenario of this file-listing fallback. Could you elaborate more about that? Such like https://github.com/weihanglo/sfz/issues/52 describing where the feature would be used.

**Comment by weihanglo** [comment]
Thank you for the PR. Unfortunately I have no time working on it. See #108.
