### ISSUE TITLE
Path issues on Windows

### ISSUE THREAD

**Issue by brundonsmith** [weihanglo/sfz#59]
```sfz v0.3.0```

Given the following directory structure:
```
foo/
  bar/
    blah.txt
```

I start the server in `foo`, and it correctly lists `bar`. I then click `bar`, and the URL becomes:
```
http://127.0.0.1:5000/foo\bar
```

Note the backslash between `foo` and `bar`. This request then also returns a `403 Forbidden`. If I change the backslash to a forward slash, I instead get a `404 Not Found`.

**Comment by weihanglo** [comment]
I've just published v0.4.0 and it should be fixed (#52).

Thanks for your report!

**Comment by brundonsmith** [comment]
Thank you! Sorry for the duplicate
