### ISSUE TITLE
Is it possible to set `charset` in content-type response header?

### ISSUE THREAD

**Issue by ypyl** [weihanglo/sfz#68]
Hello there, thanks for the great application.
I am wondering if it is possible to set/add `charset=utf-8` in Content-Type response header. Currently, I see the following type of text when I opening `yaml` file:
```
  workspace: # â— todo â—
```
but it is working well if I am replacing (via chrome extension) response header from `Content-Type: text/x-yaml`  to `Content-Type: text/x-yaml; charset utf-8`.
Is it possible somehow to set up `charset`?
thanks in advance for your help and support

**Comment by weihanglo** [comment]
Good catch! It reasonable and feasible to set UTF-8 as default.
