### ISSUE TITLE
Redirect with trailing slashes

### ISSUE THREAD

**Issue by SOF3** [weihanglo/sfz#72]
If the user requests a page `/foo/bar` but sfz (with `-r`) renders `/foo/bar/index.html`, it should first redirect the user permanently to `/foo/bar/`.

This is consistent with most HTTP server implementationns. Lack of this redirection may lead to relative path resolution issues, especially when serving generated docs (e.g. rustdoc).

**Comment by weihanglo** [comment]
Nice catch. Thanks! 
I have no spare time in the next few days. Will take a look when everything goes well. Sorry about that.

**Comment by weihanglo** [comment]
Thank you for the PR. Unfortunately I have no time working on it. See #108.
