### ISSUE TITLE
How open to stylistic changes in the UI are we?

### ISSUE THREAD

**Issue by mu-arch** [weihanglo/sfz#80]
For example I wanted to add the ability to view more info like sizes, number of files, last edit times, alternate layout options, a slide out layout options panel, better mobile support, and previews. We could offer a flag like --simple or --advanced (depending on which version became default to show or hide the additional information.

**Comment by weihanglo** [comment]
From my own need, a simple one is enough, but I like the idea of showing details behind a flag. Just need to take dependency-bloating into account.

**Comment by weihanglo** [comment]
I am open to any front-end related enhancement, such like layout and mobile support. For the server I prefer to keep it simple.

**Comment by weihanglo** [comment]
Thank you for the PR. Unfortunately I have no time working on it. See #108.
