### ISSUE TITLE
Option for coop and coep headers

### ISSUE THREAD

**Issue by HKalbasi** [weihanglo/sfz#83]
Several features of browser is not enabled due specture, unless a page declare itself as cross origin isolated by sending [coop and coep headers](https://web.dev/coop-coep/) to the browser. Notably, `sharedArrayBuffer` feature need those headers, which is required for testing rust programs with thread in web assembly. A `--coi` flag, similar to `--cors` that enables these headers would be great.

**Comment by weihanglo** [comment]
Could you elaborate more on the benefit of enabling `sharedArrayBuffer` for sfz? I have no idea the relations between them.

**Comment by HKalbasi** [comment]
It is useful for web developing. In my case, I'm trying to add rust analyzer to play.rust-lang.org . I serve the playground build folder via sfz, and everything is fine, except ra-wasm that isn't working because of `sharedArrayBuffer`. I think web developing is also the use case for `--cors`?
