### ISSUE TITLE
Support auto-reload

### ISSUE THREAD

**Issue by Folyd** [weihanglo/sfz#87]
Hope **sfz** supports auto-reload the page when the HTML files have been changed. 👏👏

**Comment by weihanglo** [comment]
Good idea. I have been thinking about this for a while. Off top of my head, sfz could learn something from mdbook: https://github.com/rust-lang/mdBook/blob/5921f598174938787ce5613f5d0c9e5851226a69/src/cmd/watch.rs#L108-L164

**Comment by weihanglo** [comment]
Thank you for the PR. Unfortunately I have no time working on it. See #108.
