### ISSUE TITLE
Allow users to set user-defined style

### ISSUE THREAD

**Issue by tat3** [weihanglo/sfz#89]
## Scenario

Sometimes I want to use sfz to display a list of files with long names.
I then use the browser's developer tools or edit style.css directly and re-build it to see the full file names.
To solve this problem, I initially thought that the number of columns and width should be configurable as command line options.
However, I felt that a more generic feature was needed to avoid the mass production of detailed front-end options in the future.

## Suggestion

Add a `--style <style>` option to the command line so that user-defined css will work for file listing pages.

For example, use the following.

```bash
$ sfz -p 4000 --style 'li { width: 400px; }'
```

## Remark

I have already implemented this feature in my fork.
If you feel this feature is a good one, I would like to submit a pull request.

**Comment by weihanglo** [comment]
Interesting! I see the use case. Could you share your fork?

**Comment by tat3** [comment]
Thank you!

Of course I will share it in #91.

**Comment by weihanglo** [comment]
Sorry I just relocated to a new place and has a lot of things to deal with. I'll come back and reconsider this feature afterwards. Thanks for your patience!

**Comment by tat3** [comment]
I understand.
It is fine when you have time!

**Comment by funkyfuture** [comment]
i would expect that once this is implemented and available, people will ask for an option to point to an css file. and in my opinion that would be preferable over a cli option / inlined styles.

**Comment by tat3** [comment]
Sorry for the very late reply! @funkyfuture 

I initially thought the same thing, but finally concluded that that feature was either not needed or not a priority in the current situation.
Because it is only a short hand for `sfz --style 'cat /path/to/style.css'`.(single quote is back quote)

**Comment by funkyfuture** [comment]
well yeah, that's a way to do it.

i'd then recommend to include this usage in the docs, but use the nowadays common bash syntax for command output extrapolation: `$(cat PATH)`

**Comment by weihanglo** [comment]
Thank you for the PR. Unfortunately I have no time working on it. See #108.
