### ISSUE TITLE
🥇 use sfz to serve static file in porduction stage 🚀 

### ISSUE THREAD

**Issue by alfuhigi** [weihanglo/sfz#90]
Hi everyone !
it is my pleasure to thank you for your fantastic repo, actually I start using sfz in Experiment purpose behind Nginx Reverse Proxy for serve static file like single page application by using container and share sfz builder and make it as runtime for other container .It work fine for me !, it will be alternative to pm2,serve for me

so, my question is!, is safe to use sfz tool in production stage ?

**Comment by weihanglo** [comment]
Thank you! I am glad this tool helps you. But sorry, I won't recommend anyone uses this in production. It's not polished in terms of performance and security. I built it as an alternative of `python3 -m http.server`, and I won't use that python server in production, neither.

There are more mature tools for single page applications out there. I currently cannot recall any but I believe you can find them. Thanks!

**Comment by weihanglo** [comment]
Closing as it is nothing to track. Thank you!
