### ISSUE TITLE
416 Range Not Satisfiable

### ISSUE THREAD

**Issue by henry40408** [weihanglo/sfz#95]
https://github.com/weihanglo/sfz/blob/4dbd5fb51b9a084ac755baf46c100603113aa576/src/server/send.rs#L206

- Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/416
- Specification: https://httpwg.org/specs/rfc7233.html#status.416

**Comment by weihanglo** [comment]
Thank you for the PR. Unfortunately I have no time working on it. See #108.
