### ISSUE TITLE
Proper logging

### ISSUE THREAD

**Issue by henry40408** [weihanglo/sfz#96]
# Proposal

We should use nginx default combined log format. Since [nginx is widely used](https://news.netcraft.com/archives/2022/08/26/august-2022-web-server-survey.html) nowadays and many logging services (I won't advertise them here) can parse nginx log messages without any configuration.

I extract the following log format from nginx 1.21.6 Docker image:

`$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"`

I ran a nginx Docker container on my laptop with the following command in sfz project directory:

`docker run --rm -it -p 8080:80 -v $PWD:/usr/share/nginx/html nginx:1.21.6`

...and the following curl command:

`curl http://localhost:8080/Cargo.toml`

...and I got the following log message in nginx Docker container:

`172.17.0.1 - - [20/Sep/2022:12:03:29 +0000] "GET /Cargo.toml HTTP/1.1" 200 1535 "-" "curl/7.79.1" "-"`

According to the same nginx documentation, I think that we should log the following information:

- remote address
- local time
- HTTP method, path, query parameters and HTTP version
- status code
- bytes sent: since nginx supports compression, I will elaborate more in the following section

# Out of Scope

I think maybe we can ignore the following segments for now since sfz usually runs locally:

- HTTP Basic Auth username, denoted as `$remote_user`
- HTTP referrer, denoted as `$http_referrer`
- `X-Forwarded-For`, denoted as `$http_x_forwarded_for`

# Other consideration

### Ordinary response body

I run the nginx Docker container with the following configuration to enable gzip:

```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    gzip on;
    gzip_types text/html;
    gzip_disable "msie6";

    include /etc/nginx/conf.d/*.conf;
}
```

...and put the following HTML document under project directory (255 bytes):

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <title></title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="css/style.css" rel="stylesheet">
</head>

<body>
  <h1>Document</h1>
</body>

</html>
```

First curl command (without compression):

```
curl -v http://localhost:8080/
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.21.6
< Date: Tue, 20 Sep 2022 12:12:25 GMT
< Content-Type: text/html
< Content-Length: 255
< Last-Modified: Tue, 20 Sep 2022 12:09:08 GMT
< Connection: keep-alive
< ETag: "6329ad64-ff"
< Accept-Ranges: bytes
<
<!DOCTYPE html>
<html lang="en">

<head>
  <title></title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="css/style.css" rel="stylesheet">
</head>

<body>
  <h1>Document</h1>
</body>

</html>
* Connection #0 to host localhost left intact
```

```
curl http://localhost:8080/ | wc -c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   255  100   255    0     0  20354      0 --:--:-- --:--:-- --:--:-- 85000
     255
```

...and get the following log message from nginx Docker container:

`172.17.0.1 - - [20/Sep/2022:12:12:55 +0000] "GET / HTTP/1.1" 200 255 "-" "curl/7.79.1" "-"`

### Compressed response body

Same nginx configuration, same HTML document, different curl command:

```
curl -v --compressed http://localhost:8080/
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.79.1
> Accept: */*
> Accept-Encoding: deflate, gzip
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.21.6
< Date: Tue, 20 Sep 2022 12:15:15 GMT
< Content-Type: text/html
< Last-Modified: Tue, 20 Sep 2022 12:09:08 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< ETag: W/"6329ad64-ff"
< Content-Encoding: gzip 👈 confirmed that gzip compression is enabled for this request
<
<!DOCTYPE html>
<html lang="en">

<head>
  <title></title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="css/style.css" rel="stylesheet">
</head>

<body>
  <h1>Document</h1>
</body>

</html>
* Connection #0 to host localhost left intact
```

```
curl --compressed -v http://localhost:8080/ | wc -c
*   Trying 127.0.0.1:8080...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.79.1
> Accept: */*
> Accept-Encoding: deflate, gzip
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.21.6
< Date: Tue, 20 Sep 2022 12:15:41 GMT
< Content-Type: text/html
< Last-Modified: Tue, 20 Sep 2022 12:09:08 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< ETag: W/"6329ad64-ff"
< Content-Encoding: gzip
<
{ [209 bytes data]
100   198    0   198    0     0  13182      0 --:--:-- --:--:-- --:--:-- 39600
* Connection #0 to host localhost left intact
     255
```

...and I get the following log message from nginx Docker container:

`172.17.0.1 - - [20/Sep/2022:12:15:41 +0000] "GET / HTTP/1.1" 200 209 "-" "curl/7.79.1" "-"`

Noted that bytes sent by nginx now becomes 209 instead of 255, so it turns out nginx is able to calculate compressed response body and log it, which is the goal we were unable to achieve in #97.

I will try my best to collect compressed response body size so we can put it in log message.

**Comment by weihanglo** [comment]
Thank you for the PR. Unfortunately I have no time working on it. See #108.
